// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type WeatherRequest struct {
	Latitude  *float64 `form:"latitude,optional"`
	Longitude *float64 `form:"longitude,optional"`
	IP        string   `form:"ip,optional"`
}

type WeatherResponse struct {
	Temperature float64 `json:"temperature"`
	Description string  `json:"description"`
	City        string  `json:"city"`
	Icon        string  `json:"icon"` // Add icon field for weather icon
}
