// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"weatherapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// get weather by latitude and longitude
				Method:  http.MethodGet,
				Path:    "/weather",
				Handler: GetWeatherHandler(serverCtx),
			},
		},
	)
}
